apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-app
  template:
    metadata:
      labels:
        app: auth-app
    spec:
      containers:
        - name: auth-app
          image: kittiphatphong/auth_start:v1
          ports:
            - containerPort: 9000
      imagePullSecrets:
        - name: regcred


